### ISSUE TITLE
Django 1.7: AttributeError: 'module' object has no attribute 'StrAndUnicode' 

### ISSUE THREAD

**Issue by groovecoder** [jbalogh/jingo#66]
In [our massive update from Django 1.4 to 1.7](https://github.com/mozilla/kuma/pull/3073), I caught our `jingo.monkey` patch call in `manage.py` using a removed feature of Django?
```
Traceback (most recent call last):
  File "./manage.py", line 46, in <module>
    import jingo.monkey
  File "/home/vagrant/src/vendor/src/jingo/jingo/monkey.py", line 60, in <module>
    class SafeStrAndUnicode(django.utils.encoding.StrAndUnicode):
AttributeError: 'module' object has no attribute 'StrAndUnicode'
```
`StrAndUnicode` was [deprecrated in 1.5](https://docs.djangoproject.com/en/1.8/releases/1.5/) and is [removed as of 1.7](https://docs.djangoproject.com/en/1.8/releases/1.7/).

**Comment by groovecoder** [comment]
Okay, I'm dumb and simply didn't use the latest code that already fixed this. But I'll file another issue to make a 0.8 tag & release on PyPI that includes the fix.
